# NUMPY NOTES

Numpy is written in C

In [1]:
import numpy as np

In [3]:
a = [1,2,3]

In [4]:
b = np.array(a)

In [5]:
b

array([1, 2, 3])

SHALLOW COPY - y is a pointer into the memory of x - reassigning y will actually change the location in memory.
<br><br>
Unless you explcitly say .copy() then it creates a DEEP COPY

In [6]:
c = np.arange(12)

In [7]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
c.shape

(12,)

In [10]:
c.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])